version: 2

seeds:
  - name: CUST_AZ12
    config:
      schema: raw
      quote_columns: false

  - name: cust_info
    config:
      schema: raw
      quote_columns: false

  - name: LOC_A101
    config:
      schema: raw
      quote_columns: false

  - name: prd_info
    config:
      schema: raw
      quote_columns: false

  - name: PX_CAT_G1V2
    config:
      schema: raw
      quote_columns: false

  - name: sales_details
    config:
      schema: raw
      quote_columns: false
